module.exports = {
    Crud: [
        'Create',
        'Read',
        'Update',
        'Find Project By Name',
    ],
    CrudOptions: [
        'Project',
        'Expense',
        'Earning',
        'Image',
        'TimeSheet',
        'Main Menu'
    ],
    CreateProjectList: [
        'name',
        'address',
        'address2',
        'city_code',
        'client_name',
        'user_name',
        'status',
        'started',
    ],
    CreateExpenseList: [
        'category',
        'subcategory',
        'amount',
        'status',
        // 'createdBy',
        // 'isArtipro',
        'createdAt',
    ],
    CreateEarningList: [
        'amount',
        'category',
        'size',
        'details',
        'status',
    ],
    CreateImageList: [
        'project_id',
        'user_id',
        'url',
        'ref',
    ],
    CreateTimeSheetList: [
        'started',
        'finished',
        'status',
        'isArtipro',
    ],

    // UpdateOptions: [
    //     'Update Project',
    //     'Update Expense',
    //     'Update Earning',
    //     'Update Image',
    //     'Update TimeSheet',
    // ],

    UpdateProjectList: [
        'name',
        'address',
        'city_code',
        'status',
        'started',
        'finished',
        'delete',
        'exit',
    ],

    UpdateExpensesList: [
        'category',
        'subcategory',
        'amount',
        'status',
        'isArtipro',
        'isApproved',
        'createdAt',
        'delete',
        'exit',
    ],

    UpdateEarningsList: [
        'amount',
        'category',
        'size',
        'details',
        'status',
        'paidAt',
        'delete',
        'exit',
    ],

    UpdateImagesList: [
        'amount',
        'category',
        'size',
        'details',
        'status',
        'paidAt',
        'delete',
        'exit',
    ],
    UpdateTimeSheetList: [
        'started',
        'finished',
        'status',
        'isArtipro',
        'delete',
        'exit',
    ],
}